# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='学生姓名')),
                ('age', models.IntegerField(verbose_name='学生年龄')),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')])),
                ('go_school', models.DateField(verbose_name='入学日期')),
                ('sclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Myclass')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='教师姓名')),
                ('age', models.IntegerField(verbose_name='教师年龄')),
                ('sex', models.IntegerField(choices=[(0, 'female'), (1, 'male')])),
            ],
        ),
        migrations.AddField(
            model_name='myclass',
            name='teacher',
            field=models.ManyToManyField(to='app02.Teacher'),
        ),
    ]
