# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='teacher',
            field=models.ManyToManyField(related_name='mclass', to='app02.Teacher'),
        ),
    ]
