# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-02 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20181102_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myclass',
            name='teacher',
            field=models.ManyToManyField(to='app02.Teacher'),
        ),
    ]
