# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='作者名')),
                ('birth', models.DateTimeField(verbose_name='生日')),
                ('sex', models.PositiveSmallIntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='性别')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='书籍名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='书籍价格')),
                ('num', models.PositiveIntegerField(unique=True, verbose_name='编号')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='出版社名称')),
                ('addr', models.CharField(max_length=128, verbose_name='地址')),
                ('create_time', models.DateField(auto_now_add=True, max_length=64, verbose_name='成立日期')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app02.Publisher', verbose_name='外键关联Publisher'),
        ),
        migrations.AddField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='app02.Book', verbose_name='多对多关联Book'),
        ),
    ]
