# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', through='app02.Book_Author', to='app02.Book', verbose_name='多对多关联Book'),
        ),
        migrations.AddField(
            model_name='book_author',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Author'),
        ),
        migrations.AddField(
            model_name='book_author',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.Book'),
        ),
    ]
