# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_auto_20181108_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='book',
        ),
    ]
