# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_remove_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='bid',
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
