# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-20 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xyh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='name',
            field=models.CharField(max_length=12),
        ),
    ]
