# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
