# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-28 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20181128_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='p_name',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='路由别名'),
        ),
    ]
