# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book_author',
            unique_together=set([('aid', 'bid')]),
        ),
    ]
