# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app04', '0002_auto_20181108_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_author',
            old_name='aid',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book_author',
            old_name='bid',
            new_name='book',
        ),
        migrations.AlterUniqueTogether(
            name='book_author',
            unique_together=set([('author', 'book')]),
        ),
    ]
