# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='head_img',
            field=models.CharField(default='/static/frontend/head_portrait/logo@2x.png', max_length=256, verbose_name='个人头像'),
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=1, max_length=64, verbose_name='加密的密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='token_create_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='title',
            field=models.CharField(max_length=32, verbose_name='课时名称'),
        ),
    ]
