# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 07:36
from __future__ import unicode_literals

import app01.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t1',
            name='hooby',
            field=app01.models.MyChar(default='111', max_length=32),
            preserve_default=False,
        ),
    ]
