# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181106_0805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t1',
            options={'verbose_name': 'app01_t1'},
        ),
        migrations.AddField(
            model_name='t1',
            name='sex',
            field=models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'none')], default=1),
            preserve_default=False,
        ),
    ]
