# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20181106_0815'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='t1',
            table=None,
        ),
    ]
