# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 11:26
from __future__ import unicode_literals

import app01.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20181106_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='t1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField(max_length=32)),
                ('create_time', models.DateField(auto_now_add=True)),
                ('edit_time', models.DateField(auto_now=True)),
                ('hooby', app01.models.MyChar(max_length=32)),
                ('sex', models.SmallIntegerField(choices=[(1, 'male'), (2, 'female'), (3, 'none')])),
            ],
            options={
                'verbose_name': 'app01_t1',
            },
        ),
    ]
