# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_t1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='author', to='app01.Book', verbose_name='多对多关联Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='app01.Publisher', verbose_name='外键关联Publisher'),
        ),
    ]
