# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0008_auto_20181108_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', through='app01.Book_Author', to='app01.Book', verbose_name='多对多关联Book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='app01.Publisher', verbose_name='外键关联Publisher'),
        ),
        migrations.AddField(
            model_name='book_author',
            name='aid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Author'),
        ),
        migrations.AddField(
            model_name='book_author',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Book'),
        ),
    ]
