# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-08 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_auto_20181108_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='bid',
        ),
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(related_name='authors', to='app01.Book', verbose_name='多对多关联Book'),
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
