# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.IntegerField(choices=[(1, '篮球'), (2, '足球'), (3, '双色球')], default=1),
        ),
    ]
