# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181116_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.CharField(choices=[(1, '篮球'), (2, '足球'), (3, '双色球')], default=1, max_length=10),
        ),
    ]
