# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-17 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_hobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='hobby',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
