# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('phone', models.CharField(default=1, max_length=11, unique=True, verbose_name='手机号')),
                ('email', models.CharField(max_length=128, verbose_name='邮箱')),
            ],
        ),
    ]
