# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='email',
            field=models.CharField(max_length=24, verbose_name='邮箱'),
        ),
    ]
