# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20181115_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='email',
            new_name='em',
        ),
    ]
