# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20181115_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女'), (3, '保密')], verbose_name='性别'),
        ),
    ]
